image: node:latest

stages:
  - build
  - lint
  - test

job_build:
  stage: build
  script:
    - npm install

job_lint:
  stage: lint
  script:
    - npm run pjv --silent
    - npm run eslint --silent

job_test:
  stage: test
  script:
    - npm test
