image: node:latest

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:lint:
  script:
    - npm run pjv --silent
    - npm run eslint --silent

test:node:
  script:
    - npm test
