version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "rps"
    ports:
      - 33306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
